### ISSUE TITLE
Issue when importing 'switch trunk'

### ISSUE THREAD

**Issue by DDinVA** [fortinetdev/terraform-provider-fortiswitch#5]
When attempting to use the import {} of existing trunks, the plugin crashes.  I can only create this output if the target resource is in the same location as the import block.  Nested modules show only the following:

│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
" Configuration for import target does not exist
fortiswitch_switch_trunk.switch_trunk["MY_TRUNK_THAT_DOES_EXIST"] does not exist.
"
I've tried 1.1.3 as well and upgraded to 7.0.6.

Stack trace from the terraform-provider-fortiswitch_v1.1.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1054f967c]

goroutine 29 [running]:
github.com/terraform-providers/terraform-provider-fortiswitch/fortiswitch.resourceSwitchTrunkRead(0x140007ae100, {0x105839440, 0x140001a6488})
        github.com/terraform-providers/terraform-provider-fortiswitch/fortiswitch/resource_switch_trunk.go:286 +0xdc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x105995c50?, {0x105995c50?, 0x140006c05d0?}, 0xd?, {0x105839440?, 0x140001a6488?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:811 +0x130
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140005400e0, {0x105995c50, 0x140006c05d0}, 0x1400079e1a0, {0x105839440, 0x140001a6488})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1117 +0x408
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140003e6048, {0x105995c50?, 0x1400054eb70?}, 0x140005221c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:708 +0x5b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140002e8aa0, {0x105995c50?, 0x1400054e180?}, 0x14000296000)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x228
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x105961fe0, 0x140002e8aa0}, {0x105995c50, 0x1400054e180}, 0x14000618100, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000211000, {0x105995c50, 0x1400054e0c0}, {0x10599a520, 0x140002fc180}, 0x140005b8fc0, 0x14000181d10, 0x105fe4928, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xb58
google.golang.org/grpc.(*Server).handleStream(0x14000211000, {0x10599a520, 0x140002fc180}, 0x140005b8fc0)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 71
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x13c

Error: The terraform-provider-fortiswitch_v1.1.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by MaxxLiu22** [comment]
Hi @DDinVA ,

Thank you for bringing this issue to my attention. Could you please provide more details, such as how you’ve defined your Terraform configuration and what the existing trunk interface looks like? On my side, I’ve tried importing the resource both directly and within a nested module, and both methods worked as expected.
```
root@liang:~/terraform/fsw/github5# terraform import module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk test
module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk: Importing from ID "test"...
module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk: Import prepared!
  Prepared fortiswitch_switch_trunk for import
module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk: Refreshing state... [id=test]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Thanks,
Maxx

**Comment by DDinVA** [comment]
> Hi @DDinVA ,
> 
> Thank you for bringing this issue to my attention. Could you please provide more details, such as how you’ve defined your Terraform configuration and what the existing trunk interface looks like? On my side, I’ve tried importing the resource both directly and within a nested module, and both methods worked as expected.
> 
> ```
> root@liang:~/terraform/fsw/github5# terraform import module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk test
> module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk: Importing from ID "test"...
> module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk: Import prepared!
>   Prepared fortiswitch_switch_trunk for import
> module.switch_trunk_module.fortiswitch_switch_trunk.my_trunk: Refreshing state... [id=test]
> 
> Import successful!
> 
> The resources that were imported are shown above. These resources are now in
> your Terraform state and will henceforth be managed by Terraform.
> ```
> 
> Thanks, Maxx

Importing it manually doesn't error out, but doesn't actually import it either.  Here's the architecture:

client_consumer (main.tf w/ module to network_pattern/module) --> network_pattern/module/trunk (main.tf with module to shared_module) --> shared_module/trunk (this is where the resource configuration is for the resource)

General setup:

1) tf call to target endpoint w/ http to v2/cmdb/switch/trunk
2) Matching existing trunks w/ name to target_list of var.switch_trunk (list of new or mod'd trunk ports)
3) New ports (create) are handled by the consumer module 'config_trunks'
4) matched, existing ports are imported via an import block:

import { for_each.local.existing_trunk_list to module.consumer[each.key].module.pattern[each.key].resource.resource_name[each.key] id = each.value

Hopefully that helps

**Comment by MaxxLiu22** [comment]
Hi @DDinVA ,

Thank you for the information. I was able to reproduce this issue when using two nested modules to access the resource. I have reported it to the development team for further investigation.

Thanks,
Maxx

**Comment by DDinVA** [comment]
> Hi @DDinVA ,
> 
> Thank you for the information. I was able to reproduce this issue when using two nested modules to access the resource. I have reported it to the development team for further investigation.
> 
> Thanks, Maxx

Please note that if you move the resource into the same 'module' (e.g., put the resource and the import block in main.tf), the crash occurs as well.  It's not limited to nested modules.

**Comment by MaxxLiu22** [comment]
Hi @DDinVA ,

Thank you for your note! I found that my crash was caused by not providing the credential information for the FortiSwitch provider. Ideally, this should raise a warning instead of causing a crash, but this might not be the case for your situation.

You mentioned using an import block in main.tf. I was wondering if it would be convenient for you to provide a simple example? In our workflow, we usually perform imports through the CLI. If we define a subprocess in main.tf for importing, running main.tf typically locks the state file, which causes the import process to fail when attempting to write to the state file.

Thank you in advance for your guidance!

**Comment by MaxxLiu22** [comment]
Hi @DDinVA,

We’ve just released Terraform FSW version 1.1.5. When you have a moment, could you please give it a try and let me know if the issue persists?

Thank you,
Maxx

**Comment by MaxxLiu22** [comment]
Hi,

I will go ahead and close this case for now. Please feel free to reopen it or create a new one if you have any further questions.

Thanks,
Maxx
